<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProductSkuMappingController extends Controller
{
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function show($id)
    {

    }

    public function store(Request $request)
    {

    }

    public function update($id)
    {

    }

    public function delete($id) {

    }
}
